package com.github.jlgrock.informatix.workmanager.domain.assignment

import com.github.jlgrock.informatix.workmanager.domain.attachment.Attachment
import com.github.jlgrock.informatix.workmanager.domain.batch.Batch
import com.github.jlgrock.informatix.workmanager.domain.useraccount.UserAccount
import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

import javax.persistence.*
import javax.validation.constraints.NotNull
/**
 *
 */
@Entity
@Table(name="assignments")
@ToString
@EqualsAndHashCode
class Assignment {

    @Id
    @NotNull
    @GeneratedValue
    Integer id

    @OneToOne(targetEntity = Batch.class, fetch = FetchType.EAGER)
    @JoinColumn(nullable = false, name = "batch_id")
    Batch batch

    @OneToOne(targetEntity = UserAccount.class, fetch = FetchType.EAGER)
    @JoinColumn(name = "user_account_id")
    UserAccount userAccount

    @Column(name="num_records")
    int numberOfRecords

    @OneToOne(targetEntity = Attachment.class, cascade=CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(nullable = true, name="assignment_attachment_id")
    Attachment originalAssignment

    @OneToOne(targetEntity = Attachment.class, cascade=CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(nullable = true, name="completed_attachment_id")
    Attachment completedAssignment

    @Column(name="billable_hours")
    Double billableHours

    @Column(name="is_auto_generated")
    boolean isAutoGenerated

}
