package com.github.jlgrock.informatix.workmanager.domain.assignment
import com.github.jlgrock.informatix.workmanager.domain.attachment.AttachmentDTO
import com.github.jlgrock.informatix.workmanager.domain.useraccount.UserAccountDTO
import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString
/**
 *
 */
@ToString
@EqualsAndHashCode
class AssignmentDTO {

    int id

    UserAccountDTO userAccount

    int numberOfRecords

    AttachmentDTO originalAssignment

    AttachmentDTO completedAssignment

    Double billableHours

    boolean isAutoGenerated

    AssignmentDTO(Assignment assignmentIn) {
        if (assignmentIn == null) {
            return
        }
        id = assignmentIn.id
        if (assignmentIn.userAccount != null) {
            userAccount = new UserAccountDTO(assignmentIn.userAccount)
        }
        numberOfRecords = assignmentIn.numberOfRecords
        if (assignmentIn.originalAssignment != null) {
            originalAssignment = new AttachmentDTO(assignmentIn.originalAssignment)
        }
        if (assignmentIn.completedAssignment != null) {
            completedAssignment = new AttachmentDTO(assignmentIn.completedAssignment)
        }
        billableHours = assignmentIn.billableHours
        isAutoGenerated = assignmentIn.isAutoGenerated
    }
}
