package com.github.jlgrock.informatix.workmanager.services
import com.github.jlgrock.informatix.workmanager.domain.assignment.Assignment
import com.github.jlgrock.informatix.workmanager.domain.assignment.AssignmentRepository
import com.github.jlgrock.informatix.workmanager.domain.assignment.HoursDTO
import com.github.jlgrock.informatix.workmanager.domain.attachment.Attachment
import com.github.jlgrock.informatix.workmanager.domain.batch.Batch
import com.github.jlgrock.informatix.workmanager.domain.batch.BatchRepository
import com.github.jlgrock.informatix.workmanager.domain.useraccount.UserAccount
import com.github.jlgrock.informatix.workmanager.domain.useraccount.UserAccountRepository
import com.github.jlgrock.informatix.workmanager.exceptions.AssignmentException
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.dao.EmptyResultDataAccessException
import org.springframework.http.MediaType
import org.springframework.stereotype.Service

import java.time.LocalDateTime
/**
 *
 */
@Service
class AssignmentService {

    @Autowired
    AssignmentRepository assignmentRepository

    @Autowired
    UserAccountRepository userAccountRepository

    @Autowired
    BatchRepository batchRepository

    Assignment get(int id) {
        assignmentRepository.findOne(id)
    }

    void delete(int id) {
        try {
            assignmentRepository.delete(id)
        } catch (EmptyResultDataAccessException e) {
            throw new AssignmentException(e)
        }
    }

    Assignment addNewAssignment(int userId, int batchId, String name, String contentType, byte[] data) {

        UserAccount userAccount = userAccountRepository.findOne(userId)
        Batch batch = batchRepository.findOne(batchId)

        Attachment originalAssignment = new Attachment([
                fileName: name,
                uploadDate: LocalDateTime.now(),
                numberOfBytes: data.size(),
                mediaType: MediaType.parseMediaType(contentType),
                data: data]);

        // TODO process file to determine number of records
        Assignment assignment = new Assignment([
                batch: batch,
                userAccount: userAccount,
                numberOfRecords: 34, //TODO fix after processing
                originalAssignment: originalAssignment,
                isAutoGenerated: false
        ])
        assignmentRepository.save(assignment)
        //TODO send email

    }

    Assignment addAutoGeneratedCompletedAssignment(int batchId, int userId, String name, String contentType, byte[] data) {

        UserAccount userAccount = userAccountRepository.findOne(userId)
        Batch batch = batchRepository.findOne(batchId)

        Attachment completedAssignment = new Attachment([
                fileName: name,
                uploadDate: LocalDateTime.now(),
                numberOfBytes: data.size(),
                mediaType: MediaType.parseMediaType(contentType),
                data: data
        ])

        // TODO process file to determine number of records
        Assignment assignment = new Assignment([
                batch: batch,
                userAccount: userAccount,
                numberOfRecords: 34, //TODO fix after processing
                completedAssignment: completedAssignment,
                isAutoGenerated: true
        ])

        assignmentRepository.save(assignment)
    }

    Assignment completeAssignment(int assignmentId, String name, String contentType, byte[] data) {
        Assignment assignment = assignmentRepository.findOne(assignmentId)

        Attachment completedAssignment = new Attachment([
                fileName: name,
                uploadDate: LocalDateTime.now(),
                numberOfBytes: data.size(),
                mediaType: MediaType.parseMediaType(contentType),
                data: data
        ])

        assignment.completedAssignment = completedAssignment

        assignmentRepository.save(assignment)
    }

    Assignment getAssignmentForHours(int id) {
        Assignment assignment = assignmentRepository.findOne(id)

        if (assignment.completedAssignment == null) {
            throw new AssignmentException("Cannot set hours until assignment has been completed")
        }
        assignment
    }
    Assignment setHours(int assignmentId, HoursDTO hoursDTO) {
        Assignment assignment = getAssignmentForHours(assignmentId)
        assignment.billableHours = hoursDTO.hours

        assignmentRepository.save(assignment)
    }

    Assignment clearHours(int assignmentId) {
        Assignment assignment = getAssignmentForHours(assignmentId)
        assignment.billableHours = null

        assignmentRepository.save(assignment)
    }
}
